# Importing the Required Libraries

In [24]:
import pandas as pd

# Loading the Dataset

In [ ]:
dataset= pd.read_csv("expense.csv")
dataset.head()

      Month Expense_Category   Amount
0   january       house_rent  75000.0
1   january        utilities  12000.0
2  february       house_rent  75000.0
3  february        utilities      NaN
4     march       house_rent  77000.0

# Filling The Null Values

In [26]:
dataset['Amount'] = dataset['Amount'].fillna(0)
dataset.head()

      Month Expense_Category   Amount
0   january       house_rent  75000.0
1   january        utilities  12000.0
2  february       house_rent  75000.0
3  february        utilities      0.0
4     march       house_rent  77000.0

# Creating the Series

In [28]:
dataset['Amount']= pd.to_numeric(dataset['Amount'],errors='coerce')
dataset

       Month Expense_Category   Amount
0    january       house_rent  75000.0
1    january        utilities  12000.0
2   february       house_rent  75000.0
3   february        utilities      0.0
4      march       house_rent  77000.0
5      march        marketing  18000.0
6      march        utilities  11500.0
7      april       house_rent  78000.0
8      april        utilities      0.0
9      april        marketing  22000.0
10       may       house_rent  79000.0
11       may        utilities  11800.0
12       may        marketing  25000.0
13      june       house_rent  80000.0
14      june        utilities      0.0
15      june        marketing  24000.0
16      july       house_rent  81000.0
17      july        utilities  13000.0
18    august        marketing      0.0
19    august        utilities  14000.0

In [32]:
month_expense = pd.Series(data = dataset['Amount'].values, index = dataset['Month'])
sort_expense= month_expense.sort_index()
total_expense= sort_expense.sum()
print(f"Months :: {sort_expense}")
print(f"Total Expense :: {total_expense}")

Months :: Month
april       22000.0
april           0.0
april       78000.0
august          0.0
august      14000.0
february        0.0
february    75000.0
january     12000.0
january     75000.0
july        81000.0
july        13000.0
june        80000.0
june            0.0
june        24000.0
march       18000.0
march       11500.0
march       77000.0
may         79000.0
may         11800.0
may         25000.0
dtype: float64
Total Expense :: 696300.0