# Importing required Libraries

In [37]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Loading the dataset

In [38]:
data = pd.read_csv("../Datasets/random_dataset_with_missing_values.csv")
data

   ID       Name   Age   Salary Department
0   1   Person_1   NaN  74131.0         IT
1   2   Person_2  46.0      NaN         IT
2   3   Person_3  32.0  46023.0        NaN
3   4   Person_4  25.0      NaN  Marketing
4   5   Person_5   NaN  97221.0        NaN
5   6   Person_6   NaN  94820.0        NaN
6   7   Person_7   NaN  30769.0        NaN
7   8   Person_8  40.0      NaN         IT
8   9   Person_9  28.0      NaN         IT
9  10  Person_10   NaN  94925.0        NaN

# Mean Technique

In [39]:
df_mean_filled = data.copy()

# Numerical columns ke liye mean fill
df_mean_filled['Age'] = df_mean_filled['Age'].fillna(df_mean_filled['Age'].mean())
df_mean_filled['Salary'] = df_mean_filled['Salary'].fillna(df_mean_filled['Salary'].mean())
#df_mean_filled['Department'] = df_mean_filled['Department'].fillna(df_mean_filled['Department'].mean())

df_mean_filled.head(10)

   ID       Name   Age   Salary Department
0   1   Person_1  34.2  74131.0         IT
1   2   Person_2  46.0  72981.5         IT
2   3   Person_3  32.0  46023.0        NaN
3   4   Person_4  25.0  72981.5  Marketing
4   5   Person_5  34.2  97221.0        NaN
5   6   Person_6  34.2  94820.0        NaN
6   7   Person_7  34.2  30769.0        NaN
7   8   Person_8  40.0  72981.5         IT
8   9   Person_9  28.0  72981.5         IT
9  10  Person_10  34.2  94925.0        NaN

# Median Technique

In [40]:
df_median_filled = data.copy()

# Numerical columns ke liye median fill
df_median_filled['Age'] = df_median_filled['Age'].fillna(df_median_filled['Age'].median())
df_median_filled['Salary'] = df_median_filled['Salary'].fillna(df_median_filled['Salary'].median())

df_median_filled.head(10)

   ID       Name   Age   Salary Department
0   1   Person_1  32.0  74131.0         IT
1   2   Person_2  46.0  84475.5         IT
2   3   Person_3  32.0  46023.0        NaN
3   4   Person_4  25.0  84475.5  Marketing
4   5   Person_5  32.0  97221.0        NaN
5   6   Person_6  32.0  94820.0        NaN
6   7   Person_7  32.0  30769.0        NaN
7   8   Person_8  40.0  84475.5         IT
8   9   Person_9  28.0  84475.5         IT
9  10  Person_10  32.0  94925.0        NaN

# Mode Technique

In [41]:
df_mode_filled = data.copy()

# Har column ke liye mode se fill
for column in ['Age', 'Salary', 'Department']:
    mode_value = df_mode_filled[column].mode()[0]
    df_mode_filled[column] = df_mode_filled[column].fillna(mode_value)

df_mode_filled.head(10)

   ID       Name   Age   Salary Department
0   1   Person_1  25.0  74131.0         IT
1   2   Person_2  46.0  30769.0         IT
2   3   Person_3  32.0  46023.0         IT
3   4   Person_4  25.0  30769.0  Marketing
4   5   Person_5  25.0  97221.0         IT
5   6   Person_6  25.0  94820.0         IT
6   7   Person_7  25.0  30769.0         IT
7   8   Person_8  40.0  30769.0         IT
8   9   Person_9  28.0  30769.0         IT
9  10  Person_10  25.0  94925.0         IT

# Arbitrary Technique

In [42]:
df_arbitrary_filled = data.copy()

# Custom arbitrary values se fill karna
df_arbitrary_filled['Age'] = df_arbitrary_filled['Age'].fillna(99)
df_arbitrary_filled['Salary'] = df_arbitrary_filled['Salary'].fillna(99999)
df_arbitrary_filled['Department'] = df_arbitrary_filled['Department'].fillna('Unknown')

df_arbitrary_filled.head(10)

   ID       Name   Age   Salary Department
0   1   Person_1  99.0  74131.0         IT
1   2   Person_2  46.0  99999.0         IT
2   3   Person_3  32.0  46023.0    Unknown
3   4   Person_4  25.0  99999.0  Marketing
4   5   Person_5  99.0  97221.0    Unknown
5   6   Person_6  99.0  94820.0    Unknown
6   7   Person_7  99.0  30769.0    Unknown
7   8   Person_8  40.0  99999.0         IT
8   9   Person_9  28.0  99999.0         IT
9  10  Person_10  99.0  94925.0    Unknown

# End of distribution

In [43]:
df_end_dist_filled = data.copy()

# End of distribution: mean + 3*std
for column in ['Age', 'Salary']:
    end_value = df_end_dist_filled[column].mean() + 3 * df_end_dist_filled[column].std()
    df_end_dist_filled[column] = df_end_dist_filled[column].fillna(end_value)

# For categorical column, we can treat end distribution as "Rare" value
df_end_dist_filled['Department'] = df_end_dist_filled['Department'].fillna('Rare')

df_end_dist_filled.head(10)

   ID       Name       Age         Salary Department
0   1   Person_1  60.21538   74131.000000         IT
1   2   Person_2  46.00000  158425.880472         IT
2   3   Person_3  32.00000   46023.000000       Rare
3   4   Person_4  25.00000  158425.880472  Marketing
4   5   Person_5  60.21538   97221.000000       Rare
5   6   Person_6  60.21538   94820.000000       Rare
6   7   Person_7  60.21538   30769.000000       Rare
7   8   Person_8  40.00000  158425.880472         IT
8   9   Person_9  28.00000  158425.880472         IT
9  10  Person_10  60.21538   94925.000000       Rare