# Importing required libraries

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
from sklearn.datasets import load_iris 
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeRegressor 
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_digits
from sklearn.datasets import load_linnerud
from sklearn.metrics import mean_absolute_error
#from sklearn.datasets import load_diabetes
from sklearn.preprocessing import LabelEncoder

# Loading Dataset of Clothes

In [53]:
clothes= pd.read_csv("clothes_price_prediction_data.csv")
clothes.head()

          Brand Category  Color Size Material  Price
0   New Balance    Dress  White   XS    Nylon    182
1   New Balance    Jeans  Black   XS     Silk     57
2  Under Armour    Dress    Red    M     Wool    127
3          Nike    Shoes  Green    M   Cotton     77
4        Adidas  Sweater  White    M    Nylon    113

In [54]:
x=clothes.drop(columns=['Price'])
y=clothes["Price"]

# Encoding the Labels

In [55]:
encoder = LabelEncoder()
clothes["Brand"]= encoder.fit_transform(clothes["Brand"])
clothes["Category"]= encoder.fit_transform(clothes["Category"])
clothes["Color"]= encoder.fit_transform(clothes["Color"])
clothes["Size"]= encoder.fit_transform(clothes["Size"])
clothes["Material"]= encoder.fit_transform(clothes["Material"])

# Viewing Again

In [56]:
clothes.head()

   Brand  Category  Color  Size  Material  Price
0      1         0      4     4         2    182
1      1         2      0     4         4     57
2      5         0      3     1         5    127
3      2         3      2     1         0     77
4      0         4      4     1         2    113

# Splitting the data

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

# Loading the regressor

In [58]:
reg = DecisionTreeRegressor()
reg.fit(x_train,y_train)

ValueError: could not convert string to float: 'Puma'

# Predictions

In [ ]:
y_pred = reg.predict(x_test)

ValueError: could not convert string to float: 'Nike'

# Mean Absolute Error

In [ ]:
MSE = mean_absolute_error(y_pred,y_test)
print(MSE)

NameError: name 'y_pred' is not defined