# Importing Required Libraries

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import CategoricalNB

# Loading the dataset and viewing first 5 rows

In [28]:
data= pd.read_csv("seattle-weather.csv")
data.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

# Dividing a Column into Other Columns

In [29]:
data['date']=pd.to_datetime(data['date']).dt.strftime('%Y-%m-%d')
data['Year']=pd.to_datetime(data['date']).dt.year
data['Month']=pd.to_datetime(data['date']).dt.month
data['Day']=pd.to_datetime(data['date']).dt.day
data = data.drop(columns=['date'])
data.head()

   precipitation  temp_max  temp_min  wind  weather  Year  Month  Day
0            0.0      12.8       5.0   4.7  drizzle  2012      1    1
1           10.9      10.6       2.8   4.5     rain  2012      1    2
2            0.8      11.7       7.2   2.3     rain  2012      1    3
3           20.3      12.2       5.6   4.7     rain  2012      1    4
4            1.3       8.9       2.8   6.1     rain  2012      1    5